# Generated by Django 4.0.2 on 2022-08-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woven_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='cpassword',
        ),
    ]
