# Generated by Django 4.0.2 on 2022-08-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woven_app', '0002_remove_signup_cpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addeducationdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=50)),
                ('previousacademic', models.CharField(max_length=122)),
                ('profession', models.TextField(null=True)),
                ('standard', models.TextField(null=True)),
                ('board_university', models.TextField(null=True)),
            ],
        ),
    ]
