# Generated by Django 4.0.2 on 2022-08-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woven_app', '0002_alter_contact_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('fullname', models.CharField(max_length=122)),
                ('aadhaar', models.CharField(max_length=12)),
                ('phoneno', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
