# Generated by Django 4.0.2 on 2022-08-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woven_app', '0003_addeducationdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parentaldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathername', models.CharField(max_length=20)),
                ('fatheroccupation', models.CharField(max_length=30)),
                ('fatherphonenumber', models.CharField(max_length=12)),
                ('mothername', models.CharField(max_length=20)),
                ('motheroccupation', models.CharField(max_length=30)),
                ('motherphonenumber', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
